tio:
  websocket:
    server:
      port: 9876
      heartbeat-timeout: 60000
    cluster:
      enabled: true
      group: true
      redis:
        ip: 127.0.0.1
        port: 6379
server:
  port: 8081
