tio:
  websocket:
    server:
      port: 9876
      heartbeat-timeout: 60000
    ssl:
      enabled: false
      keystore: classpath:ssl/tio.jks
      truststore: classpath:ssl/tio.jks
      password: 123456
    cluster:
      enabled: false
      #群组 集群，default false
      group: true
      user: true
      ip: true
      channel: true
      redis:
        ip: 127.0.0.1
        port: 6379
server:
  port: 8081